application: daily-log
version: 1-0-b1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /scripts
  static_dir: scripts
  
- url: /images
  static_dir: images
    
- url: /.*
  script: jr.py
